layout("fr");
press("GUI");
delay(500);
type("sécurité windows")
delay(2500);
press("ENTER");
delay(600);
press("TAB");
delay(200);
press("TAB");
delay(200);
press("DOWN");
delay(200);
press("ENTER");
delay(200);
press("TAB");
delay(200);
press("TAB");
delay(200);
press("TAB");
delay(200);
press("TAB");
delay(200);
press("ENTER");
delay(200);
press("SPACE");
delay(500);
press("SHIFT TAB");
delay(500);
press("ENTER");
delay(500);
press("ALT F4");